Sejlklub23/Models/Reservation.cs
using System.ComponentModel.DataAnnotations;

namespace Sejlklub23.Models
{
    public class Reservation
    {
        public int Id { get; set; }
        [Required]
        public DateTime StartOfLocation { get; set; }
        [Required]
        public int LocationDuration { get; set;}
        [Required]
        public bool IsReturned { get; set; }
        [Required]
        public int BoatId{ get; set; }
        [Required]
        public int MemberId{ get; set; }
        public Reservation() { }
       
        public Reservation(int id, DateTime startOfLoacation, int locationDuration, bool isReturned, int boatId, int memberId)
        {
            Id = id;
            StartOfLocation = startOfLoacation;
            LocationDuration = locationDuration;
            IsReturned = isReturned;
            BoatId = boatId;
            MemberId = memberId;
        }
    }
}

Sejlklub23/Models/Reservations.cs
using System.ComponentModel.DataAnnotations;

namespace Sejlklub23.Models
{
    public class Reservations
    {
        public int Id { get; set; }
        [Required]
        public DateTime StartOfLocation { get; set; }
        [Required]
        public int LocationDuration { get; set;}
        [Required]
        public bool IsReturned { get; set; }
        /*Missing list of Boat
        [Required]
        public Boats BoatId{ get; set; }
        */
        /*Missing list of Members
        [Required]
        public Members MemberId{ get; set; }
        */
        public Reservations(int id, DateTime startOfLoacation, int locationDuration, bool isReturned)
        {
            Id = id;
            StartOfLocation = startOfLoacation;
            LocationDuration = locationDuration;
            IsReturned = isReturned;
        }
    }
}

Sejlklub23/Pages/Reservations/CreateReservation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sejlklub23.Models;
using Sejlklub23.Interfaces;

namespace Sejlklub23.Pages.Reservations
{
    public class CreateReservationModel : PageModel
    {
        private IReservationRepository reservationRepository;
        private IBoatRepository boatRepository;
        private IMemberRepository memberRepository;
        private Dictionary<int, Member> Members {get; set;}
        private List<Boat> Boats { get; set;}
        public SelectList MemberList { get; set; }
        public SelectList BoatList { get; set; }
        [BindProperty]
        public Reservation NewReservation { get; set; }
        public string ErrorMessage { get; set; }

        public CreateReservationModel(IReservationRepository repo, IMemberRepository mRepo, IBoatRepository bRepo)
        {
            boatRepository = bRepo;
            memberRepository = mRepo;
            Members = memberRepository.GetAllMembers();
            Boats = boatRepository.GetAllBoats();
            reservationRepository = repo;
            MemberList = new SelectList( Members.Values,"Id", "Name");
            BoatList = new SelectList(Boats, "Id", "Name");
        }
        public IActionResult OnGet()
        {
           if (HttpContext.Session.GetString("MemberId") != null)
                return Page();
           return RedirectToPage("/Members/LoginSystem");
        }

        public IActionResult OnPost() { 
            if (!ModelState.IsValid)
            {
                return Page();
            }
            int userId = int.Parse(HttpContext.Session.GetString("MemberId"));
            NewReservation.MemberId = userId;
            try {

                reservationRepository.AcceptableReservation(NewReservation);
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return Page();
            }
            ErrorMessage = string.Empty;
            reservationRepository.CreateReservation(NewReservation);
            return RedirectToPage("Index");
        }
    }
}

Sejlklub23/Pages/Reservations/DeleteReservation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sejlklub23.Interfaces;
using Sejlklub23.Models;

namespace Sejlklub23.Pages.Reservations
{
    public class DeleteReservationModel : PageModel
    {
        private IReservationRepository _repo;

        //[BindProperty]
        public Reservation DeleteReservation { get; set; }


        public DeleteReservationModel(IReservationRepository repo)
        {
            _repo = repo;
        }
        public IActionResult OnGet(int deleteId)
        {
            DeleteReservation = _repo.GetReservation(deleteId);
            return Page();
        }

        public IActionResult OnPostDelete(int id)
        {
            _repo.DeleteReservation(id);
            return RedirectToPage("Index");
        }

        public IActionResult OnGetCancel()
        {
            return RedirectToPage("Index");
        }
    }
}

Sejlklub23/Pages/Reservations/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sejlklub23.Interfaces;
using Sejlklub23.Models;

namespace Sejlklub23.Pages.Reservations
{
    public class IndexModel : PageModel
    {
        private IReservationRepository reservationRepository;
        [BindProperty]
        public List<Reservation> Reservations { get; private set; }    
        public IndexModel(IReservationRepository repo)
        {
            reservationRepository = repo;
        }
        public void OnGet()
        {
            Reservations = reservationRepository.GetAllReservations();
        }
    }
}

Sejlklub23/Pages/Reservations/ReturnBoat.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Sejlklub23.Models;
using Sejlklub23.Services;
using Sejlklub23.Interfaces;

namespace Sejlklub23.Pages.Reservations
{
    public class ReturnBoatModel : PageModel
    {
        private IReservationRepository _reservationRepository;
        public List<string> Feedback { get; set; }
        public List<string> Problem { get; set; }
        public string Message { get; set; }
        public int NumOfHours { get; set; }
        public int MaxOfHours { get; set; }
        private List<Reservation> _reservs { get; set; }
    [BindProperty]
        public Reservation ReservationToChange { get; set; }

        public ReturnBoatModel(IReservationRepository Repo)
        {
            _reservationRepository = Repo;
        }

        public void OnGet(int returnBoat)
        {
            _reservs = _reservationRepository.GetAllReservations();
            ReservationToChange = _reservationRepository.GetReservation(returnBoat);
            MaxOfHours = 12;
            for (int i = 0; i< _reservs.Count; i++)
            {
                if (_reservs[i].StartOfLocation > ReservationToChange.StartOfLocation.AddHours(ReservationToChange.LocationDuration))
                {
                    double j = (_reservs[i].StartOfLocation - ReservationToChange.StartOfLocation.AddHours(ReservationToChange.LocationDuration)).TotalHours;
                    if (MaxOfHours < j)
                        MaxOfHours = Convert.ToInt32(j);
                }
            }
        }

        public IActionResult OnPostReturned() 
        {
            if (Message != null)
            Feedback.Add(Message);
            ReservationToChange.IsReturned = true;
            _reservationRepository.DeleteReservation(ReservationToChange.Id);
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostProblem()
        {
            if (Message != null)
                Problem.Add(Message);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostCancel()
        {
            if (NumOfHours <= 0 && NumOfHours > MaxOfHours)
                return Page();
            ReservationToChange.LocationDuration += NumOfHours;
            return RedirectToPage("Index");
        }
    }
}

Sejlklub23/Pages/Reservations/UpdateReservation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sejlklub23.Interfaces;
using Sejlklub23.Models;

namespace Sejlklub23.Pages.Reservations
{
    public class UpdateReservationModel : PageModel
    {
        private IReservationRepository _reservationRepository;
        private IBoatRepository boatRepository;
        private IMemberRepository memberRepository;
        private Dictionary<int, Member> Members { get; set; }
        private List<Boat> Boats { get; set; }
        public SelectList MemberList { get; set; }
        public SelectList BoatList { get; set; }
        [BindProperty]
        public Reservation ReservationToUpdate { get; set; }
        public string ErrorMessage { get; set; }

        public UpdateReservationModel(IReservationRepository repo, IMemberRepository mRepo, IBoatRepository bRepo)
        {
            boatRepository = bRepo;
            memberRepository = mRepo;
            Members = memberRepository.GetAllMembers();
            Boats = boatRepository.GetAllBoats();
            _reservationRepository = repo;
            MemberList = new SelectList(Members.Values, "Id", "Name");
            BoatList = new SelectList(Boats, "Id", "Name");
        }

        public void OnGet(int id)
        {
            ReservationToUpdate = _reservationRepository.GetReservation(id);
        }

        public IActionResult OnPostUpdate()
        {
            try
            {
                _reservationRepository.AcceptableReservation(ReservationToUpdate);
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return Page();
            }
            _reservationRepository.UpdateReservation(ReservationToUpdate);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostDelete()
        {
            _reservationRepository.DeleteReservation(ReservationToUpdate.Id);
            return RedirectToPage("Index");
        }

        public IActionResult OnGetCancel()
        {
            return RedirectToPage("Index");
        }
    }
}

Sejlklub23/Pages/Reservations/CreateReservation.cshtml
@page
@model Sejlklub23.Pages.Reservations.CreateReservationModel
@{
    ViewData["Title"] = "Reserve boat";
}

<h1>Reserve boat</h1>
<form method="post">@* 
    <div class="form-group">
         <label class="control-label">Member</label>
                <select asp-for="@Model.NewReservation.MemberId" asp-items="@Model.MemberList" class="form-control">
            <option value="">--Select a member--</option>
        </select> 

    </div> *@
    <div class="form-group">
        <label class="control-label">Boat</label>
        <select asp-for="@Model.NewReservation.BoatId" asp-items="@Model.BoatList" class="form-control">
            <option value="">--Select a boat--</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="@Model.NewReservation.StartOfLocation" class="control-label"></label>
        <input asp-for="@Model.NewReservation.StartOfLocation" class="form-control" />
        <span asp-validation-for="@Model.NewReservation.StartOfLocation" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.NewReservation.LocationDuration" class="control-label"></label>
        <input asp-for="@Model.NewReservation.LocationDuration" class="form-control" />
        <span asp-validation-for="@Model.NewReservation.LocationDuration" class="text-danger"></span>
    </div>
    
    <div class=" form-group">
        <input type="submit" value="Create booking" class="btn btn-primary" />
        <input type="submit" value="Test Book" asp-asp-page-handler="Test" class="btn btn-primary" />
        <label asp-for="@Model.ErrorMessage" class="danger-text"></label>
    </div>


</form>

Sejlklub23/Pages/Reservations/DeleteReservation.cshtml
@page
@using Sejlklub23.Interfaces;
@inject IBoatRepository bRepo;
@inject IMemberRepository mRepo;
@model Sejlklub23.Pages.Reservations.DeleteReservationModel
@{
    ViewData["Title"] = "Delete reservation";
}

<h1>Delete event</h1>
<form method="post">
    <div class="form-group">
        <label>Id</label> : @Model.DeleteReservation.Id <br />
        <label>Boat</label> : @bRepo.GetBoat(Model.DeleteReservation.BoatId).Name <br />
        <label>Member</label> : @mRepo.GetMember(Model.DeleteReservation.MemberId).Name <br />
        <label>Start</label> : @Model.DeleteReservation.StartOfLocation <br />
        <label>Duration</label> : @Model.DeleteReservation.LocationDuration <br />
        <input type="submit" asp-page-handler="Delete" asp-route-id="@Model.DeleteReservation.Id" class="btn btn-danger" value="Delete reservation" />

        <input type="submit" value="Cancel" class="btn btn-warning" asp-page-handler="Cancel" />
    </div>
</form>

Sejlklub23/Pages/Reservations/Index.cshtml
@page
@using Sejlklub23.Models;
@using Sejlklub23.Interfaces;
@inject IMemberRepository mRepo;
@inject IBoatRepository bRepo;
@model Sejlklub23.Pages.Reservations.IndexModel
@{
    ViewData["Title"] = "Reservations";
}
<h1>List of boats</h1>
<p>
    <a asp-page="CreateReservation">Create reservations</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Start</th>
            <th>Duration</th>
            <th>Returned</th>
            <th>Boat</th>
            <th>Member</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Reservation r in Model.Reservations)
        {
            <tr>
                <td>@r.Id</td>
                <td>@r.StartOfLocation</td>
                <td>@r.LocationDuration</td>
                <td>@r.IsReturned</td>
                <td>@bRepo.GetBoat(r.BoatId).Name</td>
                <td>@mRepo.GetMember(r.MemberId).Name</td>
                @if (HttpContext.Session.GetString("MemberId") != null)
                {
                    @if (r.StartOfLocation > DateTime.Now && r.MemberId == int.Parse(HttpContext.Session.GetString("MemberId")))
                    {
                        <td><a asp-page="UpdateReservation" asp-route-id="@r.Id">Edit</a></td>
                        <td><a asp-page="DeleteReservation" asp-route-deleteId="@r.Id">Delete</a></td>
                    }
                    else if (r.MemberId == int.Parse(HttpContext.Session.GetString("MemberId")) && r.StartOfLocation <= DateTime.Now)
                    {
                        <td><a asp-page="ReturnBoat" asp-route-returnBoat="@r.Id">Return or extand</a></td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

Sejlklub23/Pages/Reservations/ReturnBoat.cshtml
@page
@model Sejlklub23.Pages.Reservations.ReturnBoatModel
@{
    ViewData["Title"] = "Return Boat";
}

<h1>current situation of the boat</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="@Model.Feedback" class="control-label"></label>
        <input asp-for="@Model.Feedback" class="form-control" />
        <span asp-validation-for="@Model.Feedback" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.NumOfHours" class="control-label" value="extend the location of the boat in hour(between 0 and @Model.MaxOfHours)"></label>
        <input asp-for="@Model.NumOfHours" class="form-control" />
    </div>
    <div class=" form-group">
        <input type="submit" value="the boat is returned" asp-page-handler="Returned" class="btn btn-primary" />
        <input type="submit" value="signal a problem" asp-page-handler="Problem" class="btn btn-primary" />
        <input type="submit" value="extand or cancel" asp-page-handler="Cancel" class="btn btn-primary" />
    </div>
</form>

Sejlklub23/Pages/Reservations/UpdateReservation.cshtml
@page
@model Sejlklub23.Pages.Reservations.UpdateReservationModel
@{
    ViewData["Title"] = "Update reservation";
}
<h1>Reserve boat</h1>
<form method="post">
    <input type="hidden" asp-for="@Model.ReservationToUpdate.Id" />
    <div class="form-group">
        <label class="control-label">Member</label>
        <select asp-for="@Model.ReservationToUpdate.MemberId" asp-items="@Model.MemberList" class="form-control">
            <option value="">--Select a member--</option>
        </select>

    </div>
    <div class="form-group">
        <label class="control-label">Boat</label>
        <select asp-for="@Model.ReservationToUpdate.BoatId" asp-items="@Model.BoatList" class="form-control">
            <option value="">--Select a boat--</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="@Model.ReservationToUpdate.StartOfLocation" class="control-label"></label>
        <input asp-for="@Model.ReservationToUpdate.StartOfLocation" class="form-control" />
        <span asp-validation-for="@Model.ReservationToUpdate.StartOfLocation" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.ReservationToUpdate.LocationDuration" class="control-label"></label>
        <input asp-for="@Model.ReservationToUpdate.LocationDuration" class="form-control" />
        <span asp-validation-for="@Model.ReservationToUpdate.LocationDuration" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Update" asp-page-handler="Update" class="btn btn-primary" />
        <input type="submit" value="Delete" asp-page-handler="Delete" class="btn btn-primary" />
        <label asp-for="@Model.ErrorMessage" class="danger-text"></label>
    </div>


</form>